library(readxl)
library(writexl)
library(ggplot2)
library(ggpubr)
library(dplyr)
uptake<-read_excel("glucose uptake.xlsx")
d<-dist(uptake[,1])
h<-hclust(d)
plot(h, xlab = "", ylab=("Distance"),sub="Euclidean Complete Method")
rect.hclust(h, k = 3, border = 2:5)
